//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSUEventHubRepository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategorySubscriptions = new HashSet<CategorySubscription>();
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<CategorySubscription> CategorySubscriptions { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
