//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSUEventHubRepository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Reccomendations = new HashSet<Reccomendation>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Reccomendation> Reccomendations { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
