//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSUEventHubRepository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CategorySubscriptions = new HashSet<CategorySubscription>();
            this.Reccomendations = new HashSet<Reccomendation>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<CategorySubscription> CategorySubscriptions { get; set; }
        public virtual ICollection<Reccomendation> Reccomendations { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
